services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "162003"
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./ECOMMERCE-BE-fast
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./ECOMMERCE-BE-fast/.env
    depends_on:
      - mysql
    volumes:
      - ./ECOMMERCE-BE-fast:/app
  
  # frontend:
  #   build:
  #     context: ./fe-ecommerce
  #   container_name: ecommerce-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production

  frontend-dev:
    build:
      context: ./fe-ecommerce
      target: builder
    container_name: ecommerce-frontend-dev
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./fe-ecommerce:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    profiles:
      - dev
volumes:
  mysql_data:

