services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "162003"
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: ./ECOMMERCE-BE-fast
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./ECOMMERCE-BE-fast/.env
    depends_on:
      - mysql
    volumes:
      - ./ECOMMERCE-BE-fast:/app

volumes:
  mysql_data:
